#data <- read.csv.sql("household_power_consumption.txt", sep=";",sql='select * from file where Date = "1/2/2007" or Date="2/2/2007"')
#data$Date <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")

png("plot4.png")
par(mfrow=c(2,2))
with(data,{
  plot(Date,Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
  plot(Date,Voltage,type="l",xlab="datetime",ylab="Voltage")
  plot(Date, Sub_metering_1,col="black",type="l",ylab="Energy sub metering", xlab="")
  lines(Date, Sub_metering_2,col="red")
  lines(Date, Sub_metering_3,col="blue")
  legend("topright", pch = "_", col = c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(Date, Global_reactive_power,type="l",xlab="")
})
dev.off()